# Generated by Django 3.2.4 on 2022-03-11 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.zone')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveSmallIntegerField()),
                ('cutin', models.PositiveIntegerField(default=0)),
                ('cutoff', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('R', 'Regular'), ('F', 'Fullfee')], default='R', max_length=1)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.college')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.program')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='programs',
            field=models.ManyToManyField(through='rank.CollegeProgram', to='rank.Program'),
        ),
        migrations.CreateModel(
            name='Addmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('batch', models.PositiveSmallIntegerField()),
                ('quota', models.CharField(choices=[('NOR', 'Normal Quota'), ('DAL', 'Dalit Quota'), ('FEM', 'Female Quota'), ('GOV', 'Government Quota'), ('STF', 'Teacher/Staff Quota'), ('FOR', 'Foreign Quota'), ('OTH', 'Other')], default='NOR', max_length=3)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rank', models.PositiveIntegerField(null=True)),
                ('collegeprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.collegeprogram')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rank.district')),
            ],
        ),
        migrations.AddConstraint(
            model_name='collegeprogram',
            constraint=models.UniqueConstraint(fields=('college', 'program', 'type'), name='manyToMany'),
        ),
    ]
