# Generated by Django 3.2.4 on 2021-07-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmission',
            name='rank',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addmission',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
