# Generated by Django 3.2.4 on 2021-06-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='location',
        ),
        migrations.AddField(
            model_name='college',
            name='code',
            field=models.CharField(default='PUL', max_length=3),
            preserve_default=False,
        ),
    ]
