# Generated by Django 3.2.4 on 2021-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20210705_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprogram',
            name='cutoff',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
