# Generated by Django 3.2.4 on 2021-06-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20210622_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='quota',
            field=models.CharField(choices=[('RE', 'Regular'), ('OT', 'Other')], default='RE', max_length=2),
        ),
    ]
